### ISSUE TITLE
Milestones for an initial version

### ISSUE THREAD

**Issue by carlosedp** [carlosedp/mill-aliases#1]
These are the pending tasks:

- [x] Collect all root modules that extend from trait `Aliases`
- [x] Get all method names defined for each module above with the aliases 
- [x] Get the aliased tasks for each alias
- [x] Execute the aliased tasks using the `evaluateTasks` for each Mill version
- [x] Reuse logic for the `Alias/list` command
